SELECT month(date_conso), year(date_conso), C.REFERENCE, DESIGNATION, SUM(NB_CONSO), PRIX_CONSO
FROM CONSOMMABLE AS C, CONSOMMER AS CO, SERVICE AS S, DIVISION AS D
WHERE DATE_CONSO BETWEEN '2009-01-01' AND '2009-12-31' 
AND C.REFERENCE = CO.REFERENCE
AND CO.ID_SERVICE = S.ID_SERVICE
AND S.ID_DIVISION = D.ID_DIVISION
AND D.ID_DIVISION = 'CETIAD' 
GROUP BY month(date_conso), year(date_conso), C.REFERENCE, PRIX_CONSO 
HAVING SUM(NB_CONSO) > 0;

SELECT month(date_conso), year(date_conso), C.REFERENCE, DESIGNATION, SUM(NB_CONSO), PRIX_CONSO
FROM CONSOMMABLE AS C, CONSOMMER AS CO, SERVICE AS S, DIVISION AS D
WHERE DATE_CONSO BETWEEN '2009-01-01' AND '2009-12-31' 
AND C.REFERENCE = CO.REFERENCE
AND CO.ID_SERVICE = S.ID_SERVICE
AND S.ID_DIVISION = D.ID_DIVISION
AND D.ID_DIVISION = 'CETIAD' 
GROUP BY month(date_conso), year(date_conso), C.REFERENCE, PRIX_CONSO 
HAVING SUM(NB_CONSO) > 0;